package main

import (
	"bytes"
	"io"
	"net/http"
	"net/http/httptest"
	"testing"

	"snippetbox.adpollak.net/internal/assert"
)

func TestPing(t *testing.T) {
	// 1) create ResponseRecorder object
	rr := httptest.NewRecorder()

	r, err := http.NewRequest(http.MethodGet, "/", nil)
	if err != nil {
		t.Fatal(err)
	}

	// 2) Pass it to the handler we're testing
	// Call the ping handler with the httptest.ResponseRecorder
	// and http.Request
	ping(rr, r)

	// Call Result() on http.ResponseRecorder to get the http.Response
	// generated by the ping handler
	rs := rr.Result()

	// 3) Now examine it again  after the handler returns.
	// Check status code written by ping handler is 200
	assert.Equal(t, rs.StatusCode, http.StatusOK)

	// And now check that the response body written by the ping handler
	// is equal to "OK"
	defer rs.Body.Close()
	body, err := io.ReadAll(rs.Body)
	if err != nil {
		t.Fatal(err)
	}
	bytes.TrimSpace(body)
	assert.Equal(t, string(body), "OK")
}
